riode/Areas/Admin/Controllers/SizesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using riode.Models.DataContexts;
using riode.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace riode.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SizesController : Controller
    {
        readonly RiodeDbContext db;
        public SizesController(RiodeDbContext db)
        {
            this.db = db;
        }
        public async Task<IActionResult> Index()
        {
            var sizeList = await db.Size.ToListAsync();
            return View(sizeList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Sizes size)
        {
            if (ModelState.IsValid)
            {
                await db.Size.AddAsync(size);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(size);
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (id < 1)
            {
                return NotFound();
            }
            var size = await db.Size.FirstOrDefaultAsync(b => b.Id == id);
            if (size == null)
            {
                return NotFound();
            }
            if (size.DeletedDate != null)
            {
                return NotFound();
            }
            return View(size);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute] int id, Sizes model)
        {
            if (ModelState.IsValid)
            {
                var size = await db.Size.FirstOrDefaultAsync(b => b.Id == id);
                if (size == null)
                {
                    return NotFound();
                }
                if (size.DeletedDate != null)
                {
                    return NotFound();
                }
                size.Name = model.Name;
                size.ShortName = model.ShortName;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (id < 1)
            {
                return NotFound();
            }
            var size = await db.Size.FirstOrDefaultAsync(b => b.Id == id);
            if (size == null)
            {
                return NotFound();
            }
            if (size.DeletedDate != null)
            {
                return NotFound();
            }
            return View(size);
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeletePost([FromRoute] int id)
        {
            if (id < 1)
            {
                return NotFound();
            }
            var size = await db.Size.FirstOrDefaultAsync(b => b.Id == id);
            if (size == null)
            {
                return NotFound();
            }
            if (size.DeletedDate != null)
            {
                return NotFound();
            }
            size.DeletedDate = DateTime.Now;
            await db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detail([FromRoute] int id)
        {
            if (id < 1)
            {
                return NotFound();
            }
            var size = await db.Size.FirstOrDefaultAsync(b => b.Id == id);
            if (size == null)
            {
                return NotFound();
            }
            if (size.DeletedDate != null)
            {
                return NotFound();
            }
            return View(size);
        }
    }
}

riode/Areas/Admin/Views/Sizes/Create.cshtml
@model riode.Models.Entities.Sizes
@{
    ViewData["Title"] = "Create";
}

<div style="padding:0;margin-left:240px">
    <form method="post">
        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label">
            </label>
            <div class="col-sm-10">
                <input asp-for="Name" type="text" class="form-control">
                <span asp-validation-for="Name"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ShortName" class="col-sm-2 col-form-label">
            </label>
            <div class="col-sm-10">
                <input asp-for="ShortName" type="text" class="form-control">
                <span asp-validation-for="ShortName"></span>
            </div>
        </div>
        <button type="submit" class="btn btn-out btn-success btn-square">
            Create
        </button>
    </form>
</div>

riode/Areas/Admin/Views/Sizes/Delete.cshtml
@model riode.Models.Entities.Sizes

@{
    ViewData["Title"] = "Delete";
}

<div style="padding:0;margin-left:240px">
    <form method="post">
        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label">
            </label>
            <div class="col-sm-10">
                <input asp-for="Name" disabled type="text" class="form-control">
                <span asp-validation-for="Name"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ShortName" class="col-sm-2 col-form-label">
            </label>
            <div class="col-sm-10">
                <input asp-for="ShortName" disabled type="text" class="form-control">
                <span asp-validation-for="ShortName"></span>
            </div>
        </div>
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-out btn-success btn-square">
            Delete
        </button>
    </form>
</div>

riode/Areas/Admin/Views/Sizes/Detail.cshtml
@model riode.Models.Entities.Sizes

@{
    ViewData["Title"] = "Detail";
}

<div style="padding:0;margin-left:240px">
    <div class="card">
        <div class="card-block table-border-style">
            <div class="table-responsive">
                <table class="table table-inverse">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Short Name</th>
                            <th>Created Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">@Model.Id</th>
                            <td>@Model.Name</td>
                            <td>@Model.ShortName</td>
                            <td>@Model.CreatedDate</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

riode/Areas/Admin/Views/Sizes/Edit.cshtml
@model riode.Models.Entities.Sizes

@{
    ViewData["Title"] = "Edit";
}

<div style="padding:0;margin-left:240px">
    <form method="post">
        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label">
            </label>
            <div class="col-sm-10">
                <input asp-for="Name" type="text" class="form-control">
                <span asp-validation-for="Name"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ShortName" class="col-sm-2 col-form-label">
            </label>
            <div class="col-sm-10">
                <input asp-for="ShortName" type="text" class="form-control">
                <span asp-validation-for="ShortName"></span>
            </div>
        </div>
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-out btn-success btn-square">
            Edit
        </button>
    </form>
</div>

riode/Areas/Admin/Views/Sizes/Index.cshtml
@model List<riode.Models.Entities.Sizes>
@{
    ViewData["Title"] = "Index";
}

<div style="padding:0;margin-left:240px">
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h5>Sizes</h5>
            <br />
            <a asp-controller="Sizes" asp-action="Create" class="btn btn-out btn-success btn-square">
                Create
            </a>
        </div>
        <div class="card-block table-border-style">
            <div class="table-responsive">
                <table class="table table-inverse">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Created Date</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.DeletedDate == null)
                            {

                                <tr>
                                    <th scope="row">@item.Id</th>
                                    <td>@item.Name</td>
                                    <td>@item.CreatedDate</td>
                                    <td>
                                        <a asp-route-id="@item.Id" asp-controller="Sizes" asp-action="Detail"><img style="width: 25px; height: 25px; margin: 20px" src="https://img.icons8.com/ios-glyphs/30/000000/visible--v1.png" /></a>
                                        <a asp-route-id="@item.Id" asp-controller="Sizes" asp-action="Edit"><img style="width: 25px; height: 25px; margin: 20px" src="https://img.icons8.com/external-kiranshastry-solid-kiranshastry/64/000000/external-pen-interface-kiranshastry-solid-kiranshastry.png" /></a>
                                        <a asp-route-id="@item.Id" asp-controller="Sizes" asp-action="Delete"><img style="width: 25px; height: 25px; margin: 20px" src="https://img.icons8.com/dotty/80/000000/trash.png" /></a>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>