riode/Models/Entities/Brands.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace riode.Models.Entities
{
    public class Brands
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Ad Bos Buraxila Bilmez")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Description Yazilmayib")]
        public string Description { get; set; }

        public DateTime CreatedDate { get; set; } = DateTime.Now;

        public DateTime? DeletedDate { get; set; }
    }
}

riode/Areas/Admin/Controllers/BrandsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using riode.Models.DataContexts;
using riode.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace riode.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BrandsController : Controller
    {
        readonly RiodeDbContext db;
        public BrandsController(RiodeDbContext db)
        {
            this.db = db;
        }
        public async Task<IActionResult> Index()
        {
            var brandList = await db.Brand.ToListAsync();
            return View(brandList);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async  Task<IActionResult> Create(Brands brand)
        {
            if (ModelState.IsValid)
            {
                await db.Brand.AddAsync(brand);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(brand);
        }


        public async Task<IActionResult> Edit(int id)
        {
            if (id < 1)
            {
                return NotFound();
            }
            var brand = await db.Brand.FirstOrDefaultAsync(b => b.Id == id);
            if (brand == null)
            {
                return NotFound();
            }
            if (brand.DeletedDate != null)
            {
                return NotFound();
            }
            return View(brand);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute]int id,Brands model)
        {
            if (ModelState.IsValid)
            {
                var brand = await db.Brand.FirstOrDefaultAsync(b => b.Id == id);
                if (brand == null)
                {
                    return NotFound();
                }
                if (brand.DeletedDate != null)
                {
                    return NotFound();
                }
                brand.Name = model.Name;
                brand.Description = model.Description;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (id < 1)
            {
                return NotFound();
            }
            var brand = await db.Brand.FirstOrDefaultAsync(b => b.Id == id);
            if (brand == null)
            {
                return NotFound();
            }
            if (brand.DeletedDate != null)
            {
                return NotFound();
            }
            return View(brand);
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeletePost([FromRoute] int id)
        {
                if (id < 1)
                {
                    return NotFound();
                }
                var brand = await db.Brand.FirstOrDefaultAsync(b => b.Id == id);
                if (brand == null)
                {
                    return NotFound();
                }
                if (brand.DeletedDate != null)
                {
                    return NotFound();
                }
                brand.DeletedDate = DateTime.Now;
                await db.SaveChangesAsync();

                return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detail([FromRoute] int id)
        {
            if (id < 1)
            {
                return NotFound();
            }
            var brand = await db.Brand.FirstOrDefaultAsync(b => b.Id == id);
            if (brand == null)
            {
                return NotFound();
            }
            if (brand.DeletedDate != null)
            {
                return NotFound();
            }
            return View(brand);
        }

    }
}

riode/Areas/Admin/Views/Brands/Create.cshtml
@model riode.Models.Entities.Brands
@{
    ViewData["Title"] = "Create";
}

<div style="padding:0;margin-left:240px">
    <form method="post">
        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label">
            </label>
            <div class="col-sm-10">
                <input asp-for="Name" type="text" class="form-control">
                <span asp-validation-for="Name"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Description" class="col-sm-2 col-form-label">
            </label>
            <div class="col-sm-10">
                <input asp-for="Description" type="text" class="form-control">
                <span asp-validation-for="Description"></span>
            </div>
        </div>
        <button type="submit" class="btn btn-out btn-success btn-square">
            Create
        </button>
    </form>
</div>

riode/Areas/Admin/Views/Brands/Delete.cshtml
@model riode.Models.Entities.Brands

@{
    ViewData["Title"] = "Delete";
}

<div style="padding:0;margin-left:240px">
    <form method="post">
        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label">
            </label>
            <div class="col-sm-10">
                <input asp-for="Name" disabled type="text" class="form-control">
                <span asp-validation-for="Name"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Description" class="col-sm-2 col-form-label">
            </label>
            <div class="col-sm-10">
                <input asp-for="Description" disabled type="text" class="form-control">
                <span asp-validation-for="Description"></span>
            </div>
        </div>
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-out btn-success btn-square">
            Delete
        </button>
    </form>
</div>

riode/Areas/Admin/Views/Brands/Detail.cshtml
@model riode.Models.Entities.Brands

@{
    ViewData["Title"] = "Detail";
}

<div style="padding:0;margin-left:240px">
    <div class="card">
        <div class="card-block table-border-style">
            <div class="table-responsive">
                <table class="table table-inverse">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Created Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">@Model.Id</th>
                            <td>@Model.Name</td>
                            <td>@Model.Description</td>
                            <td>@Model.CreatedDate</td>
                        </tr>
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

riode/Areas/Admin/Views/Brands/Edit.cshtml
@model riode.Models.Entities.Brands

@{
    ViewData["Title"] = "Edit";
}

<div style="padding:0;margin-left:240px">
    <form method="post">
        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label">
            </label>
            <div class="col-sm-10">
                <input asp-for="Name" type="text" class="form-control">
                <span asp-validation-for="Name"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Description" class="col-sm-2 col-form-label">
            </label>
            <div class="col-sm-10">
                <input asp-for="Description" type="text" class="form-control">
                <span asp-validation-for="Description"></span>
            </div>
        </div>
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-out btn-success btn-square">
            Edit
        </button>
    </form>
</div>

riode/Areas/Admin/Views/Brands/Index.cshtml
@model List<riode.Models.Entities.Brands>

@{
    ViewData["Title"] = "Index";
}

<div style="padding:0;margin-left:240px">
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h5>Brands</h5>
            <br />
            <a asp-controller="Brands" asp-action="Create" class="btn btn-out btn-success btn-square">
                Create
            </a>
        </div>
        <div class="card-block table-border-style">
            <div class="table-responsive">
                <table class="table table-inverse">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Created Date</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.DeletedDate == null)
                            {

                                <tr>
                                    <th scope="row">@item.Id</th>
                                    <td>@item.Name</td>
                                    <td>@item.CreatedDate</td>
                                    <td>
                                        <a asp-route-id="@item.Id" asp-controller="Brands" asp-action="Detail"><img style="width: 25px; height: 25px; margin: 20px" src="https://img.icons8.com/ios-glyphs/30/000000/visible--v1.png" /></a>
                                        <a asp-route-id="@item.Id" asp-controller="Brands" asp-action="Edit"><img style="width: 25px; height: 25px; margin: 20px" src="https://img.icons8.com/external-kiranshastry-solid-kiranshastry/64/000000/external-pen-interface-kiranshastry-solid-kiranshastry.png" /></a>
                                        <a asp-route-id="@item.Id" asp-controller="Brands" asp-action="Delete"><img style="width: 25px; height: 25px; margin: 20px" src="https://img.icons8.com/dotty/80/000000/trash.png" /></a>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>