riode/Models/Entities/Colors.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace riode.Models.Entities
{
    public class Colors
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Ad Bos Buraxila Bilmez")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Reng Kodu   Yazilmayib")]
        public string ColorCode { get; set; }

        public DateTime CreatedDate { get; set; } = DateTime.Now;

        public DateTime? DeletedDate { get; set; }
    }
}

riode/Areas/Admin/Controllers/ColorsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using riode.Models.DataContexts;
using riode.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace riode.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ColorsController : Controller
    {
        readonly RiodeDbContext db;
        public ColorsController(RiodeDbContext db)
        {
            this.db = db;
        }
        public async Task<IActionResult> Index()
        {
            var colorList = await db.Color.ToListAsync();
            return View(colorList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Colors color)
        {
            if (ModelState.IsValid)
            {
                await db.Color.AddAsync(color);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(color);
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (id < 1)
            {
                return NotFound();
            }
            var color = await db.Color.FirstOrDefaultAsync(b => b.Id == id);
            if (color == null)
            {
                return NotFound();
            }
            if (color.DeletedDate != null)
            {
                return NotFound();
            }
            return View(color);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute] int id, Colors model)
        {
            if (ModelState.IsValid)
            {
                var color = await db.Color.FirstOrDefaultAsync(b => b.Id == id);
                if (color == null)
                {
                    return NotFound();
                }
                if (color.DeletedDate != null)
                {
                    return NotFound();
                }
                color.Name = model.Name;
                color.ColorCode = model.ColorCode;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (id < 1)
            {
                return NotFound();
            }
            var color = await db.Color.FirstOrDefaultAsync(b => b.Id == id);
            if (color == null)
            {
                return NotFound();
            }
            if (color.DeletedDate != null)
            {
                return NotFound();
            }
            return View(color);
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeletePost([FromRoute] int id)
        {
            if (id < 1)
            {
                return NotFound();
            }
            var color = await db.Color.FirstOrDefaultAsync(b => b.Id == id);
            if (color == null)
            {
                return NotFound();
            }
            if (color.DeletedDate != null)
            {
                return NotFound();
            }
            color.DeletedDate = DateTime.Now;
            await db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detail([FromRoute] int id)
        {
            if (id < 1)
            {
                return NotFound();
            }
            var color = await db.Color.FirstOrDefaultAsync(b => b.Id == id);
            if (color == null)
            {
                return NotFound();
            }
            if (color.DeletedDate != null)
            {
                return NotFound();
            }
            return View(color);
        }
    }
}

riode/Areas/Admin/Views/Colors/Create.cshtml
@model riode.Models.Entities.Colors
@{
    ViewData["Title"] = "Create";
}

<div style="padding:0;margin-left:240px">
    <form method="post">
        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label">
            </label>
            <div class="col-sm-10">
                <input asp-for="Name" type="text" class="form-control">
                <span asp-validation-for="Name"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ColorCode" class="col-sm-2 col-form-label">
            </label>
            <div class="col-sm-10">
                <input asp-for="ColorCode" type="text" class="form-control">
                <span asp-validation-for="ColorCode"></span>
            </div>
        </div>
        <button type="submit" class="btn btn-out btn-success btn-square">
            Create
        </button>
    </form>
</div>

riode/Areas/Admin/Views/Colors/Delete.cshtml
@model riode.Models.Entities.Colors

@{
    ViewData["Title"] = "Delete";
}

<div style="padding:0;margin-left:240px">
    <form method="post">
        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label">
            </label>
            <div class="col-sm-10">
                <input asp-for="Name" disabled type="text" class="form-control">
                <span asp-validation-for="Name"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ColorCode" class="col-sm-2 col-form-label">
            </label>
            <div class="col-sm-10">
                <input asp-for="ColorCode" disabled type="text" class="form-control">
                <span asp-validation-for="ColorCode"></span>
                <div style="background-color:@Model.ColorCode;width:20px;height:20px; margin-top:20px;"></div>
            </div>
        </div>
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-out btn-success btn-square">
            Delete
        </button>
    </form>
</div>

riode/Areas/Admin/Views/Colors/Detail.cshtml
@model riode.Models.Entities.Colors

@{
    ViewData["Title"] = "Detail";
}

<div style="padding:0;margin-left:240px">
    <div class="card">
        <div class="card-block table-border-style">
            <div class="table-responsive">
                <table class="table table-inverse">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Color</th>
                            <th>Name</th>
                            <th>Color Code</th>
                            <th>Created Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">@Model.Id</th>
                            <td><div style="background-color:@Model.ColorCode;width:20px;height:20px;"></div></td>
                            <td>@Model.Name</td>
                            <td>@Model.ColorCode</td>
                            <td>@Model.CreatedDate</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

riode/Areas/Admin/Views/Colors/Edit.cshtml
@model riode.Models.Entities.Colors

@{
    ViewData["Title"] = "Edit";
}

<div style="padding:0;margin-left:240px">
    <form method="post">
        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label">
            </label>
            <div class="col-sm-10">
                <input asp-for="Name" type="text" class="form-control">
                <span asp-validation-for="Name"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ColorCode" class="col-sm-2 col-form-label">
            </label>
            <div class="col-sm-10">
                <input asp-for="ColorCode" type="text" class="form-control">
                <span asp-validation-for="ColorCode"></span>
            </div>
        </div>
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-out btn-success btn-square">
            Edit
        </button>
    </form>
</div>

riode/Areas/Admin/Views/Colors/Index.cshtml
@model List<riode.Models.Entities.Colors>
@{
    ViewData["Title"] = "Index";
}

<div style="padding:0;margin-left:240px">
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h5>Colors</h5>
            <br />
            <a asp-controller="Colors" asp-action="Create" class="btn btn-out btn-success btn-square">
                Create
            </a>
        </div>
        <div class="card-block table-border-style">
            <div class="table-responsive">
                <table class="table table-inverse">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Color</th>
                            <th>Color Name</th>
                            <th>Created Date</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.DeletedDate == null)
                            {

                                <tr>
                                    <th scope="row">@item.Id</th>
                                    <td><div style="background-color:@item.ColorCode;width:20px;height:20px;"></div></td>
                                    <td>@item.Name</td>
                                    <td>@item.CreatedDate</td>
                                    <td>
                                        <a asp-route-id="@item.Id" asp-controller="Colors" asp-action="Detail"><img style="width: 25px; height: 25px; margin: 20px" src="https://img.icons8.com/ios-glyphs/30/000000/visible--v1.png" /></a>
                                        <a asp-route-id="@item.Id" asp-controller="Colors" asp-action="Edit"><img style="width: 25px; height: 25px; margin: 20px" src="https://img.icons8.com/external-kiranshastry-solid-kiranshastry/64/000000/external-pen-interface-kiranshastry-solid-kiranshastry.png" /></a>
                                        <a asp-route-id="@item.Id" asp-controller="Colors" asp-action="Delete"><img style="width: 25px; height: 25px; margin: 20px" src="https://img.icons8.com/dotty/80/000000/trash.png" /></a>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>